apiVersion: v1
kind: Service
metadata:
  name: k8s-front-bff-service
spec:
  type: LoadBalancer
  selector:
    app: k8s-front-bff
  ports:
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: backend
      protocol: TCP
      port: 3001
      targetPort: 3001